### ISSUE TITLE
Browser independent UI elements

### ISSUE THREAD

**Issue by eimrek** [materialscloud-org/mc-react-structure-visualizer#2]
The current UI elements at the bottom of the visualizer can look wrong on some browsers (e.g. on mobile), see

<img src="https://github.com/materialscloud-org/mc-react-structure-visualizer/assets/8721264/3d3b3508-cf34-41ec-9acb-1078308bf1f0" width="400">

They should be implemented in a browser-independent way. Preferably with bootstrap elements, as that's a already a dependency.

**Comment by SharanRP** [comment]
I attempted to replicate this error on both a Surface Duo and an iPhone SE, (in the Windows developer options menu)but in my case, the visualizer appears to display correctly. While the content page may vary slightly, I don't believe this to be a critical issue. If I have misunderstood something or made an error, please let me know and I'll make the necessary corrections.

on Surface Duo
![image](https://github.com/materialscloud-org/mc-react-structure-visualizer/assets/136159249/847b52e8-567d-437a-a32b-786c4073aa6f)
iPhone SE
![image](https://github.com/materialscloud-org/mc-react-structure-visualizer/assets/136159249/bdc96fb7-edd2-4375-963d-b3ab415c6b9b)

**Comment by eimrek** [comment]
thanks @SharanRP. I'm not able to recreate this either with chrome, firefox or edge. This image came from a user using an iphone, which probably was running safari. But regardless, the supercell input, camera buttons and the checkboxes should be implemented with bootstrap, rather than the default html elements, as these still change depending on the browser.

**Comment by SharanRP** [comment]
@eimrek Absolutely, I'm currently working on it

**Comment by SharanRP** [comment]
@eimrek  I have opened the PR implementing these features.
